spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**
  application:
    name: web_pay

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

management:
  health:
    rabbit:
      enabled: false
