spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**
  application:
    name: web_admin

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


